[package]
name = "ssss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.11.0"
glutin = "0.28"
winit = "0.26.1"

png = "0.17.1"
palette = "0.2.1"
assert_hex = "0.2.2"

num = "0.4.0"

[profile.release]
opt-level = 3